### ISSUE TITLE
Some errors show on the tag page

### ISSUE THREAD

**Issue by syhily** [foru17/nevecoo#1]
[tag.hbs] Cannot read property 'length' of undefined

**Comment by foru17** [comment]
Thanks.I also found this issue. it seems that there is a bug of Ghost? Replace
tag.hbs with the orginal theme one to check whether the bug from,
On 周三, 4月 15, 2015 at 8:49 下午, foru17/nevecoo
reply@reply.github.com
wrote:[tag.hbs] Cannot read property 'length' of undefined

**Comment by syhily** [comment]
The same error, i was just wondering how to get the fully error message. Maybe the debug mode?

**Comment by syhily** [comment]
Ghost-1 (err):     at Object.eval (eval at <anonymous> (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:19:23)
Ghost-1 (err):     at ret (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:144:30)
Ghost-1 (err):     at ret (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:462:21)
Ghost-1 (err):
Ghost-1 (err): ERROR: [tag.hbs] Cannot read property 'length' of undefined
Ghost-1 (err):  Rendering Error Page
Ghost-1 (err):  Ghost caught a processing error in the middleware layer.
Ghost-1 (err):  TypeError: [tag.hbs] Cannot read property 'length' of undefined
Ghost-1 (err):     at downzero (/var/www/Ghost/core/server/utils/downzero.js:26:26)
Ghost-1 (err):     at Object.content (/var/www/Ghost/core/server/helpers/content.js:26:17)
Ghost-1 (err):     at Object.eval (eval at <anonymous> (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:11:72)
Ghost-1 (err):     at ret (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:144:30)
Ghost-1 (err):     at ret (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:462:21)
Ghost-1 (err):     at Object.invokePartial (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:12)
Ghost-1 (err):     at Object.invokePartialWrapper [as invokePartial](/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:47:39)
Ghost-1 (err):     at Object.eval (eval at <anonymous> (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:19:23)
Ghost-1 (err):     at ret (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:144:30)
Ghost-1 (err):     at ret (/var/www/Ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:462:21)

I got this error message on PM2 logs. I would trying to fix it. XD

**Comment by syhily** [comment]
Found The Origin Of This Error. Please Look at the loop.hbs
